config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items do
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
    end
    member do
      get 'buy'
    end
  end
  resources :users, only: [:show]
  resources :credits, except: [:edit, :update] do
    collection do
      get 'pay'
    end
  end
  resources :signups , only: [:new, :create] do
    collection do
      get 'identification'
      post 'address'
      post 'phone_number'
    end
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :validates_user, only: :address
  before_action :validates_address, only: :phone_number
  before_action :validates_phone, only: :create
  def new
  end

  def identification
    @user = User.new
  end

  def address
    @address = Address.new
  end

  def phone_number
    @user = User.new
  end

  def create
    @user.save
    Address.create(
      user: @user,
      first_name: session[:address]["first_name"],
      last_name: session[:address]["last_name"],
      first_name_kana: session[:address]["first_name_kana"],
      last_name_kana: session[:address]["last_name_kana"],
      prefecture_id: session[:address]["prefecture_id"],
      city: session[:address]["city"],
      house_number: session[:address]["house_number"],
      post_number: session[:address]["post_number"],
      phone_number: session[:address]["phone_number"]
    )
    sign_in @user unless user_signed_in?
  end
  
  private
  
  def validates_user
    session[:user] = User.new()
    session[:user][:nickname] = user_params[:nickname]
    session[:user][:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:user][:first_name] = user_params[:first_name]
    session[:user][:last_name] = user_params[:last_name]
    session[:user][:first_name_kana] = user_params[:first_name_kana]
    session[:user][:last_name_kana] = user_params[:last_name_kana]
    if Date.valid_date?(params[:birthday]["birthday(1i)"].to_i,params[:birthday]["birthday(2i)"].to_i,params[:birthday]["birthday(3i)"].to_i)
      session[:user][:birthday] = Date.new(params[:birthday]["birthday(1i)"].to_i,params[:birthday]["birthday(2i)"].to_i,params[:birthday]["birthday(3i)"].to_i)
    else
      session[:user][:birthday] = nil
    end  
    @user = User.new(
      nickname: session[:user][:nickname],
      email: session[:user][:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      first_name: session[:user][:first_name],
      last_name: session[:user][:last_name], 
      first_name_kana: session[:user][:first_name_kana], 
      last_name_kana: session[:user][:last_name_kana], 
      birthday: session[:user][:birthday],
      phone_number: "09009876543"
    )
    unless @user.valid?
      render '/signups/identification'
    end
  end
  
  def validates_address
    session[:address] = Address.new()
    session[:address][:first_name] = address_params[:first_name]
    session[:address][:last_name] = address_params[:last_name]
    session[:address][:first_name_kana] = address_params[:first_name_kana]
    session[:address][:last_name_kana] = address_params[:last_name_kana]
    session[:address][:prefecture_id] = address_params[:prefecture_id]
    session[:address][:city] = address_params[:city]
    session[:address][:house_number] = address_params[:house_number]
    session[:address][:post_number] = address_params[:post_number]
    session[:address][:phone_number] = address_params[:phone_number]

    @user = User.new
    @address = Address.new(
      user: @user,
      first_name: session[:address][:first_name],
      last_name: session[:address][:last_name],
      first_name_kana: session[:address][:first_name_kana],
      last_name_kana: session[:address][:last_name_kana],
      prefecture_id: session[:address][:prefecture_id],
      city: session[:address][:city],
      house_number: session[:address][:house_number],
      post_number: session[:address][:post_number],
      phone_number: session[:address][:phone_number]
    )
    unless @address.valid?
      render '/signups/address'
    end
  end

  def validates_phone
    @user = User.new(
      nickname: session[:user]["nickname"],
      email: session[:user]["email"],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      first_name: session[:user]["first_name"],
      last_name: session[:user]["last_name"], 
      first_name_kana: session[:user]["first_name_kana"], 
      last_name_kana: session[:user]["last_name_kana"], 
      birthday: session[:user]["birthday"],
      phone_number: user_params[:phone_number]
    )
    unless @user.valid?
      render '/signups/phone_number'
    end
  end

  def user_params
    params.require(:user).permit(:nickname,:email,:password,:password_confirmation,:first_name,:last_name,:first_name_kana,:last_name_kana,:phone_number)
  end

  def address_params
    params.require(:address).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:prefecture_id,:city,:house_number,:building,:phone_number,:post_number)
  end

end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/signups/address.html.haml
.sign-up__headder
  .sign-up__headder__content
    = link_to root_path do
      = image_tag 'logo/logo.png', class: "logo"
    .nav-bar
      .nav-bar__content
        %h5
          会員情報
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5.red
          住所登録
        .nav-bar__content__round.back-red.nav-bar__content__progress
      .nav-bar__content
        %h5
          電話番号
        .nav-bar__content__round.nav-bar__content__progress
      .nav-bar__content
        %h5
          登録完了
        .nav-bar__content__round
.sign-up
  .sign-up__content
    %h2.sign-up__content__title
      発送元・お届け先住所変更
  = form_with model: @address, url: phone_number_signups_path, local: true do |f|
    .sign-up__content__main
      .sign-up__content__main__form
        .field
          .field__label
            = f.label :first_name, "お名前(全角)"
            %span.attention
              必須
          .field-box__wrapper
            = f.text_field :first_name, class: "field__box__half", placeholder: "例)中野"
            = f.text_field :last_name, class: "field__box__half", placeholder: "例)尊"
          -unless @address.errors.full_messages_for(:last_name) == []
            .errors_messages
              苗字
              = @address.errors.messages[:last_name].to_s.delete('[ "]').sub!(/,.*/, '')
          -unless @address.errors.full_messages_for(:first_name) == []
            .errors_messages
              名前
              = @address.errors.messages[:first_name].to_s.delete('[ "]').sub!(/,.*/, '')
        .field.field-box
          .field__label
            = f.label :first_name_kana, "お名前カナ(全角)"
            %span.attention
              必須
          .field-box__wrapper
            = f.text_field :first_name_kana, class: "field__box__half", placeholder: "例)ナカノ"
            = f.text_field :last_name_kana, class: "field__box__half", placeholder: "例)タケル"
          -unless @address.errors.full_messages_for(:last_name_kana) == []
            .errors_messages
              ミョウジ
              = @address.errors.messages[:last_name_kana].to_s.delete('[ "]').sub!(/,.*/, '')
          -unless @address.errors.full_messages_for(:first_name_kana) == []
            .errors_messages
              ナマエ
              = @address.errors.messages[:first_name_kana].to_s.delete('[ "]').sub!(/,.*/, '')
        .field.field-box
          .field__label
            = f.label :post_number, "郵便番号"
            %span.attention
              必須
          = f.text_field :post_number, class: "field__box", placeholder: "例)123-456"
          -unless @address.errors.full_messages_for(:post_number) == []
            .errors_messages
              郵便番号
              = @address.errors.messages[:post_number].to_s.delete('[ "]').sub!(/,.*/, '')
        .field
          .field-label
            = f.label :prefecture, "都道府県"
            %span.attention
              必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name
          -unless @address.errors.full_messages_for(:prefecture) == []
            .errors_messages
              都道府県
              = @address.errors.messages[:prefecture].to_s.delete('[ "]').sub!(/,.*/, '')
        .field
          .field__label
            = f.label :city, "市区町村"
            %span.attention
              必須
          = f.text_field :city, class: "field__box", placeholder: "例)横浜市緑区"
          -unless @address.errors.full_messages_for(:city) == []
            .errors_messages
              市区町村
              = @address.errors.messages[:city].to_s.delete('[ "]')
        .field
          .field__label
            = f.label :house_number, "番地"
            %span.attention
              必須
          = f.text_field :house_number, class: "field__box", placeholder: "例)青山1-1-1"
          -unless @address.errors.full_messages_for(:house_number) == []
            .errors_messages
              番地
              = @address.errors.messages[:house_number].to_s.delete('[ "]')
        .field
          .field__label
            = f.label :building, "建物"
            %span.attention.arbitrary
              任意
          = f.text_field :building, class: "field__box", placeholder: "例)添木ビル108"
        .field
          .field__label
            = f.label :phone_number, "電話"
            %span.attention.arbitrary
              任意
          = f.text_field :phone_number, class: "field__box", placeholder: "例)090123456781"
          -unless @address.errors.full_messages_for(:phone_number) == []
            .errors_messages
              電話番号
              = @address.errors.messages[:phone_number].to_s.delete('[ "]').sub!(/,.*/, '')
        =f.submit "次へ進む", class: 'create-action-btn'
= render 'shared/logo_footer'

app/views/signups/create.html.haml
.sign-up__headder
  .sign-up__headder__content
    = link_to root_path do
      = image_tag 'logo/logo.png', class: "logo"
    .nav-bar
      .nav-bar__content
        %h5
          会員情報
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5
          住所登録
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5
          電話番号
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5.red
          登録完了
        .nav-bar__content__round.back-red
.sign-up.completion-of-registration
  .sign-up__content
    %h2.sign-up__content__title
      電話番号の確認
  .sign-up__content__main
    .sign-up__content__main__form
      %p.finish-sentense
        ありがとうございます
      %p.finish-sentense
        登録が完了しました
      =link_to root_path do
        .create-action-btn
          %p.start-sentense
            Furimaを始める
= render 'shared/logo_footer'

app/views/signups/identification.html.haml
.sign-up__headder
  .sign-up__headder__content
    = link_to root_path do
      = image_tag 'logo/logo.png', class: "logo"
    .nav-bar
      .nav-bar__content
        %h5.red
          会員情報
        .nav-bar__content__round.back-red.nav-bar__content__progress
      .nav-bar__content
        %h5
          住所登録
        .nav-bar__content__round.nav-bar__content__progress
      .nav-bar__content
        %h5
          電話番号
        .nav-bar__content__round.nav-bar__content__progress
      .nav-bar__content
        %h5
          登録完了
        .nav-bar__content__round
.sign-up
  .sign-up__content
    %h2.sign-up__content__title
      会員情報入力
  = form_with model: @user, url: address_signups_path, local: true do |f|
    .sign-up__content__main
      .sign-up__content__main__form
        .field__label
          = f.label :nickname, "ニックネーム"
          %span.attention
            必須
        = f.text_field :nickname, autofocus: true, class: "field__box", placeholder: "例)フリマリオ"
        -unless @user.errors.full_messages_for(:nickname) == []
          .errors_messages
            ニックネーム
            = @user.errors.messages[:nickname].to_s.delete('[ "]')
        .field
          .field__label
            = f.label :email, "メールアドレス"
            %span.attention
              必須
          = f.email_field :email, class: "field__box", placeholder: "PC・携帯どちらでも可"
          -unless @user.errors.full_messages_for(:email) == []
            .errors_messages
              E-mail
              = @user.errors.messages[:email].to_s.delete('[ "]').sub!(/,.*/, '')
        .field
          .field__label
            = f.label :password, "パスワード"
            %span.attention
              必須
          = f.password_field :password, class: "field__box", placeholder: "7文字以上の半角英数"
          = check_box_tag :check
          = label_tag :check, "パスワードを表示する", class: "check-box-label"
          -unless @user.errors.full_messages_for(:password) == []
            .errors_messages
              password
              = @user.errors.messages[:password].to_s.delete('[ "]').sub!(/,.*/, '')
        .field
          .field__label
            = f.label :password_confirmation, "パスワード確認用"
            %span.attention
              必須
          = f.password_field :password_confirmation, class: "field__box", placeholder: "もう一度入力してください"
          -unless @user.errors.full_messages_for(:password_confirmation) == []
            .errors_messages
              入力が一致しません
        %h2
          本人確認
        %p
          安心・安全にご利用いただくために、
          お客さまの本人情報の登録にご協力ください。
          他のお客さまに公開されることはありません。
        .field
          .field__label
            = f.label :first_name, "お名前(全角)"
            %span.attention
              必須
          .field-box__wrapper
            = f.text_field :first_name, class: "field__box__half", placeholder: "例)中野"
            = f.text_field :last_name, class: "field__box__half", placeholder: "例)尊"
          -unless @user.errors.full_messages_for(:last_name) == []
            .errors_messages
              苗字
              = @user.errors.messages[:last_name].to_s.delete('[ "]').sub!(/,.*/, '')
          -unless @user.errors.full_messages_for(:first_name) == []
            .errors_messages
              名前
              = @user.errors.messages[:first_name].to_s.delete('[ "]').sub!(/,.*/, '')
        .field
          .field__label
            = f.label :first_name_kana, "お名前カナ(全角)"
            %span.attention
              必須
          .field-box__wrapper
            = f.text_field :first_name_kana, class: "field__box__half", placeholder: "例)ナカノ"
            = f.text_field :last_name_kana, class: "field__box__half", placeholder: "例)タケル"
          -unless @user.errors.full_messages_for(:last_name_kana) == []
            .errors_messages
              ミョウジ
              = @user.errors.messages[:last_name_kana].to_s.delete('[ "]').sub!(/,.*/, '')
          -unless @user.errors.full_messages_for(:first_name_kana) == []
            .errors_messages
              ナマエ
              = @user.errors.messages[:first_name_kana].to_s.delete('[ "]').sub!(/,.*/, '')
        .field
          .field__label
            = f.label :birthday, "生年月日"
            %span.attention
              必須
          .field__birthday
            != sprintf(f.date_select(:birthday, prefix:'birthday',with_css_classes:'birthday_box', prompt:"--",use_month_numbers:true, start_year:Time.now.year, end_year:1900, date_separator:'%s'),'年','月')+'日'
          -unless @user.errors.full_messages_for(:birthday) == []
            .errors_messages
              生年月日
              = @user.errors.messages[:birthday].to_s.delete('[ "]')
          %h4
            ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        %h3
          「次へ進む」のボタンを押すことにより、利用規約に同意したものとみなします
        = f.submit "次へ進む", class: 'create-action-btn'
        .checklist
          %h4
            本人情報確認について
        .notes
          This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.
= render 'shared/logo_footer'

app/views/signups/new.html.haml
= render 'shared/logo_header'
.sign-up.sin-up-select
  .sign-up__content
    %h2.sign-up__content__title
      新規会員登録
    .sign-up__content__lists
      = link_to identification_signups_path do
        .sign-up__content__lists__list.mail
          %i.far.fa-envelope.icon.fa-2x
          %h4
            メールアドレスで登録する
      .sign-up__content__lists__list.facebook
        %i.fab.fa-facebook-square.icon.fa-2x
        %h4
          Facebookで登録する
      .sign-up__content__lists__list.google
        %i.fab.fa-google.icon.fa-2x
        %h4
          Googleで登録する
= render 'shared/logo_footer'

app/views/signups/phone_number.html.haml
.sign-up__headder
  .sign-up__headder__content
    = link_to root_path do
      = image_tag 'logo/logo.png', class: "logo"
    .nav-bar
      .nav-bar__content
        %h5
          会員情報
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5
          住所登録
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5.red
          電話番号
        .nav-bar__content__round.back-red.nav-bar__content__progress
      .nav-bar__content
        %h5
          登録完了
        .nav-bar__content__round
.sign-up
  .sign-up__content
    %h2.sign-up__content__title
      電話番号の確認
  = form_with model: @user, url: signups_path, local: true do |f|
    .sign-up__content__main
      .sign-up__content__main__form
        .field__label
          = f.label :phone_number, "携帯電話の番号"
          %span.attention
            必須
        = f.text_field :phone_number, autofocus: true, class: "field__box", placeholder: "09098766543"
        -unless @user.errors.full_messages_for(:phone_number) == []
          .errors_messages
            電話番号
            = @user.errors.messages[:phone_number].to_s.delete('[ "]').sub!(/,.*/, '')
        %p.phone-notes
          本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います.
        =f.submit "smsを送信する", class: 'create-action-btn'
        %p.phone-notes
          ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません
        =link_to do
          .reason-phone
            電話番号の確認が必要な理由
            %i.fas.fa-angle-right
= render 'shared/logo_footer'

app/views/signups/step1.html.haml
.sign-up__headder
  .sign-up__headder__content
    = image_tag 'logo/logo.png', class: "logo"
    .nav-bar
      .nav-bar__content
        %h5.red
          会員情報
        .nav-bar__content__round.back-red.nav-bar__content__progress
      .nav-bar__content
        %h5
          住所登録
        .nav-bar__content__round.nav-bar__content__progress
      .nav-bar__content
        %h5
          電話番号
        .nav-bar__content__round.nav-bar__content__progress
      .nav-bar__content
        %h5
          登録完了
        .nav-bar__content__round
.sign-up
  .sign-up__content
    %h2.sign-up__content__title
      会員情報入力
  = form_with do |f|
    .sign-up__content__main
      .sign-up__content__main__form
        .field__label
          = f.label :nickname, "ニックネーム"
          %span.attention
            必須
        = f.text_field :nickname, autofocus: true, class: "field__box", placeholder: "例)フリマリオ"
        .field
          .field__label
            = f.label :email, "メールアドレス"
            %span.attention
              必須
          = f.email_field :email, class: "field__box", placeholder: "PC・携帯どちらでも可"
        .field
          .field__label
            = f.label :password, "パスワード"
            %span.attention
              必須
          = f.password_field :password, class: "field__box", placeholder: "7文字以上の半角英数"
          %h4
            ※ 英字と数字の両方を含めて設定してください
          = check_box_tag :check
          = label_tag :check, "パスワードを表示する", class: "check-box-label"
        %h2
          本人確認
        %p
          安心・安全にご利用いただくために、
          お客さまの本人情報の登録にご協力ください。
          他のお客さまに公開されることはありません。
        .field
          .field__label
            = f.label :first_name, "お名前(全角)"
            %span.attention
              必須
          .field-box__wrapper
            = f.password_field :first_name, class: "field__box__half", placeholder: "例)中野"
            = f.password_field :last_name, class: "field__box__half", placeholder: "例)尊"
        .field
          .field__label
            = f.label :first_name_kana, "お名前カナ(全角)"
            %span.attention
              必須
          .field-box__wrapper
            = f.password_field :first_name_kana, class: "field__box__half", placeholder: "例)ナカノ"
            = f.password_field :last_name_kana, class: "field__box__half", placeholder: "例)タケル"
          .field
            .field__label
              = f.label :birthday, "生年月日"
              %span.attention
                必須
            != sprintf(f.date_select(:birthday, prefix:'birthday',with_css_classes:'birthday_box', prompt:"--",use_month_numbers:true, start_year:Time.now.year, end_year:1900, date_separator:'%s'),'年','月')+'日'
            %h4
              ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        %h3
          「次へ進む」のボタンを押すことにより、利用規約に同意したものとみなします
        = f.submit "次へ進む", class: 'create-action-btn'
        .checklist
          %h4
            本人情報確認について
        =link_to step2_signups_path do
          .notes
            This site is protected by reCAPTCHA and the Google Privacy Policy and Terms of Service apply.

app/views/signups/step2.html.haml
.sign-up__headder
  .sign-up__headder__content
    = image_tag 'logo/logo.png', class: "logo"
    .nav-bar
      .nav-bar__content
        %h5
          会員情報
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5.red
          住所登録
        .nav-bar__content__round.back-red.nav-bar__content__progress
      .nav-bar__content
        %h5
          電話番号
        .nav-bar__content__round.nav-bar__content__progress
      .nav-bar__content
        %h5
          登録完了
        .nav-bar__content__round
.sign-up
  .sign-up__content
    %h2.sign-up__content__title
      発送元・お届け先住所変更
  = form_with do |f|
    .sign-up__content__main
      .sign-up__content__main__form
        .field
          .field__label
            = f.label :first_name, "お名前(全角)"
            %span.attention
              必須
          .field-box__wrapper
            = f.password_field :first_name, class: "field__box__half", placeholder: "例)中野"
            = f.password_field :last_name, class: "field__box__half", placeholder: "例)尊"
        .field.field-box
          .field__label
            = f.label :first_name_kana, "お名前カナ(全角)"
            %span.attention
              必須
          .field-box__wrapper
            = f.password_field :first_name_kana, class: "field__box__half", placeholder: "例)ナカノ"
            = f.password_field :last_name_kana, class: "field__box__half", placeholder: "例)タケル"
        .field.field-box
          .field__label
            = f.label :post_number, "郵便番号"
            %span.attention
              必須
          = f.email_field :post_number, class: "field__box", placeholder: "例)123-456"
        .field
          .field-label
            = f.label :pref_id, "都道府県"
            %span.attention
              必須
          = f.select :pref_id, include_blank: :true
          -# = f.select :pref_id, Pref.all.map{|pf| [pf.name, pf.id]}, include_blank: :true
        .field
          .field__label
            = f.label :city, "市区町村"
            %span.attention
              必須
          = f.email_field :city, class: "field__box", placeholder: "例)横浜市緑区"
        .field
          .field__label
            = f.label :house_number, "番地"
            %span.attention
              必須
          = f.email_field :house_number, class: "field__box", placeholder: "例)青山1-1-1"
        .field
          .field__label
            = f.label :building, "建物"
            %span.attention.arbitrary
              任意
          = f.email_field :building, class: "field__box", placeholder: "例)添木ビル108"
        .field
          .field__label
            = f.label :phone_number, "電話"
            %span.attention.arbitrary
              任意
          = f.email_field :phone_number, class: "field__box", placeholder: "例)090123456781"
        =f.submit "次へ進む", class: 'create-action-btn'

app/views/signups/step3.html.haml
.sign-up__headder
  .sign-up__headder__content
    = image_tag 'logo/logo.png', class: "logo"
    .nav-bar
      .nav-bar__content
        %h5
          会員情報
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5
          住所登録
        .nav-bar__content__round.back-red.nav-bar__content__passing
      .nav-bar__content
        %h5.red
          電話番号
        .nav-bar__content__round.back-red.nav-bar__content__progress
      .nav-bar__content
        %h5
          登録完了
        .nav-bar__content__round
.sign-up
  .sign-up__content
    %h2.sign-up__content__title
      電話番号の確認
  = form_with do |f|
    .sign-up__content__main
      .sign-up__content__main__form
        .field__label
          = f.label :phone_number, "携帯電話の番号"
          %span.attention
            必須
        = f.text_field :phone_number, autofocus: true, class: "field__box", placeholder: "09098766543"
        %p.phone-notes
          本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います.
        =f.submit "smsを送信する", class: 'create-action-btn'
        %p.phone-notes
          ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません
        =link_to do
          .reason-phone
            電話番号の確認が必要な理由
            %i.fas.fa-angle-right