config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items do
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
    end
    member do
      get 'buy'
    end
  end
  resources :users, only: [:show]
  resources :credits, except: [:edit, :update] do
    collection do
      get 'pay'
    end
  end
  resources :signups , only: [:new, :create] do
    collection do
      get 'identification'
      post 'address'
      post 'phone_number'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to :user

  VALID_NAME_REGEX = /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/
  VALID_NAME_KANA_REGEX = /\A[ァ-ヶー－]+\z/
  VALID_PHONE_REGEX = /\A\d{10,11}\z/
  VALID_POST_REGEX = /\A\d{3}[-]\d{4}\z/

  validates :last_name,             presence: true, format: { with: VALID_NAME_REGEX }
  validates :first_name,            presence: true, format: { with: VALID_NAME_REGEX }
  validates :last_name_kana,        presence: true, format: { with: VALID_NAME_KANA_REGEX }
  validates :first_name_kana,       presence: true, format: { with: VALID_NAME_KANA_REGEX }
  validates :prefecture_id,         presence: true
  validates :city,                  presence: true
  validates :house_number,          presence: true
  validates :post_number,           presence: true, format: { with: VALID_POST_REGEX  }
  validates :phone_number,          format: { with: VALID_PHONE_REGEX  }, allow_blank: true

end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :children, class_name: 'Category', foreign_key: 'category_id', dependent: :destroy
  belongs_to :parent, class_name: 'Category', foreign_key: 'category_id', optional: :true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item  
  belongs_to :user
  validates :text,:user_id,:item_id, presence: true
end
  

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user

  validates :user_id, :customer_id, :card_id, presence: true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :deliverycharge
  belongs_to_active_hash :deliveryday
  belongs_to_active_hash :prefecture

  belongs_to :item
  belongs_to :user, optional: true

  validates :deliverycharge_id,     presence: true
  validates :deliveryday_id,        presence: true
  validates :prefecture_id,         presence: true
  validates :item_id,               presence: true
end

app/models/deliverycharge.rb
class Deliverycharge < ActiveHash::Base
  self.data = [
      {id: 1, name: '送料込み(出品者負担)'}, {id: 2, name: '着払い(購入者負担)'}
  ]
end

app/models/deliveryday.rb
class Deliveryday < ActiveHash::Base
  self.data = [
      {id: 1, name: '1~2日で発送'}, {id: 2, name: '2~3日で発送'}, {id: 3, name: '4~7日で発送'}
  ]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status
  belongs_to_active_hash :prefecture
  
  belongs_to :category
  belongs_to :user
  has_one :delivery, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :name,             presence: true, length:{maximum: 40}
  validates :text,             presence: true, length:{maximum: 1000}
  validates :price,            presence: true
  validates :status_id,        presence: true
  validates :soldout,          presence: true
  validates :user_id,          presence: true
  validates :category_id,      presence: true

  def favorite?(user)
    favorite_users.include?(user)
  end

end  

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :picture, ImageUploader
  belongs_to :item

  validates :item_id,          presence: true
  validates :picture,          presence: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
      {id: 1, name: '新品、未使用'}, {id: 2, name: '未使用に近い'}, {id: 3, name: '目立った傷汚れなし'},
      {id: 4, name: 'やや傷や汚れあり'}, {id: 5, name: '傷や汚れあり'}, {id: 6, name: '全体的に状態が悪い'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one :address, dependent: :destroy
  has_one :credit,  dependent: :destroy
  has_many :items
  has_many :deliveries
  has_many :favorites, dependent: :destroy
  has_many :comments

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/
  VALID_NAME_KANA_REGEX = /\A[ァ-ヶー－]+\z/
  VALID_PHONE_REGEX = /\A\d{10,11}\z/

  validates :email,                 presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :nickname,              presence: true, length: {maximum: 20}
  validates :last_name,             presence: true, format: { with: VALID_NAME_REGEX }
  validates :first_name,            presence: true, format: { with: VALID_NAME_REGEX }
  validates :last_name_kana,        presence: true, format: { with: VALID_NAME_KANA_REGEX }
  validates :first_name_kana,       presence: true, format: { with: VALID_NAME_KANA_REGEX }
  validates :birthday,              presence: true

  validates :phone_number,          presence: true, format: { with: VALID_PHONE_REGEX  }

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample67b
    
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_logo_footer.html.haml
.logo-footer 
  %nav
    %ul.logo-footer__clearfix
      %li プライバシーポリシー
      %li フリマ利用規約
      %li 特定商取引に関する表記
  .logo-footer__logo
    = image_tag "logo/logo-white.png", size: "140x65"

app/views/shared/_logo_header.html.haml
.logo-header
  .logo-header__image
    %span
    = link_to root_path do
      = image_tag "logo/logo.png", size: "185x49"

app/views/shared/_main_exhibition-btn.html.haml
= link_to new_item_path do
  .exhibition-btn
    .exhibition-btn__text
      出品する
    .exhibition-btn__icon
      = image_tag "icon/icon_camera.png", width: "70px", height: "70px"

app/views/shared/_main_footer.html.haml
.footer
  .footer__contents
    .footer__contents__lists
      .footer__contents__lists__list1
        .footer__contents__lists__list1__about
          FURIMAについて
        .footer__contents__lists__list1__text1
          会社概要（運営会社)
        .footer__contents__lists__list1__text2
          プライバシーポリシー
        .footer__contents__lists__list1__text3
          FURIMA利用規約
        .footer__contents__lists__list1__text4
          ポイントに関する特約

      .footer__contents__lists__list2
        .footer__contents__lists__list2__about
          FURIMAを見る
        .footer__contents__lists__list2__text1
          カテゴリー一覧
        .footer__contents__lists__list2__text2
          ブランド一覧

      .footer__contents__lists__list3
        .footer__contents__lists__list3__about
          ヘルプ＆ガイド
        .footer__contents__lists__list3__text1
          FURIMAガイド
        .footer__contents__lists__list3__text2
          FURIMAロゴ利用ガイドライン
        .footer__contents__lists__list3__text3
          お知らせ

  .footer__logo
  .footer__text
    © FURIMA

app/views/shared/_main_header.html.haml
.header
  .header__middle-box
    = link_to root_path do
      .header__middle-box__img
    .header__middle-box__search-box
      %p.header__middle-box__search-box__text
        キーワードから探す
    .header__middle-box__icon
  .header__middle-box__lower
    .header__middle-box__lower__left-box
      .header__middle-box__lower__left-box__category
        カテゴリー
      .header__middle-box__lower__left-box__brand
        ブランド
    .header__middle-box__lower__right-box
      - unless user_signed_in?
        = link_to new_user_session_path do
          .header__middle-box__lower__right-box__login
            ログイン
        =link_to new_signup_path do
          .header__middle-box__lower__right-box__sign-up
            新規会員登録
      - else
        = link_to user_path(current_user) do
          .header__middle-box__lower__right-box__sign-up
            マイページ

app/views/shared/_navigation_bar.html.haml
%nav.u-s-content__nav
  %ul
    %li
      = link_to do
        .page-transition.my-page-transition
          %p
            マイページ
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            お知らせ
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            やることリスト
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            いいね！一覧
          %i.fas.fa-chevron-right
    %li
      = link_to new_item_path do
        .page-transition
          %p
            出品する
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            出品した商品-出品中
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            出品した商品-取引中
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            出品した商品-売却済
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            購入した商品-取引中
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            購入した商品-過去の取引
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            ニュース一覧
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            評価一覧
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            ガイド
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            お問い合わせ
          %i.fas.fa-chevron-right
  %h3
    メルペイ
  %ul
    %li
      = link_to do
        .page-transition
          %p
            売上・振込申請
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            ポイント
          %i.fas.fa-chevron-right
  %h3
    設定
  %ul
    %li
      = link_to do
        .page-transition
          %p
            プロフィール
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            発送元・お届け先住所変更
          %i.fas.fa-chevron-right
    %li
      = link_to credits_path do
        .page-transition
          %p
            支払い方法
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            メール/パスワード
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            本人情報
          %i.fas.fa-chevron-right
    %li
      = link_to do
        .page-transition
          %p
            電話番号確認
          %i.fas.fa-chevron-right
    %li
      = link_to destroy_user_session_path, method: :delete do
        .page-transition
          %p
            ログアウト
          %i.fas.fa-chevron-right

app/views/shared1/_exhibition-btn.html.haml
= link_to "#" do
  .exhibition-btn
    .exhibition-btn__text
      出品する
    .exhibition-btn__icon
      = image_tag "icon/icon_camera.png", width: "80px", height: "80px"

app/views/shared1/_footer.html.haml
.footer
  .footer__contents
    .footer__contents__lists
      .footer__contents__lists__list1
        .footer__contents__lists__list1__about
          FURIMAについて
        .footer__contents__lists__list1__text1
          会社概要（運営会社)
        .footer__contents__lists__list1__text2
          プライバシーポリシー
        .footer__contents__lists__list1__text3
          FURIMA利用規約
        .footer__contents__lists__list1__text4
          ポイントに関する特約

      .footer__contents__lists__list2
        .footer__contents__lists__list2__about
          FURIMAを見る
        .footer__contents__lists__list2__text1
          カテゴリー一覧
        .footer__contents__lists__list2__text2
          ブランド一覧

      .footer__contents__lists__list3
        .footer__contents__lists__list3__about
          ヘルプ＆ガイド
        .footer__contents__lists__list3__text1
          FURIMAガイド
        .footer__contents__lists__list3__text2
          FURIMAロゴ利用ガイドライン
        .footer__contents__lists__list3__text3
          お知らせ

  .footer__logo
  .footer__text
    © FURIMA

app/views/shared1/_header.html.haml
.header
  .header__middle-box
    .header__middle-box__img
    .header__middle-box__search-box
      %p.header__middle-box__search-box__text
        キーワードから探す
    .header__middle-box__icon
  .header__middle-box__lower
    .header__middle-box__lower__left-box
      .header__middle-box__lower__left-box__category
        カテゴリー
      .header__middle-box__lower__left-box__brand
        ブランド
    .header__middle-box__lower__right-box
      .header__middle-box__lower__right-box__login
        ログイン
      .header__middle-box__lower__right-box__sign-up
        新規会員登録