config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items do
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
    end
    member do
      get 'buy'
    end
  end
  resources :users, only: [:show]
  resources :credits, except: [:edit, :update] do
    collection do
      get 'pay'
    end
  end
  resources :signups , only: [:new, :create] do
    collection do
      get 'identification'
      post 'address'
      post 'phone_number'
    end
  end
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user

  validates :user_id, :customer_id, :card_id, presence: true
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  require "payjp"
  before_action :set_credit
  before_action :move_show, only: [:index, :new]
  before_action :set_api_key, except: [:index, :new]

  def index
  end

  def new
  end

  def create
    if params[:payjp_token].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
        description: 'test',
        email: current_user.email,
        card: params[:payjp_token]
      )
      @credit = Credit.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @credit.save
        redirect_to action: "index"
      else
        redirect_to action: "new"
      end
    end
  end

  def show
    customer = Payjp::Customer.retrieve(@credit.customer_id)
    @credit_information = customer.cards.retrieve(@credit.card_id)
  end

  def destroy
    customer = Payjp::Customer.retrieve(@credit.customer_id)
    customer.delete
    if @credit.destroy
      redirect_to action: "index"
    else 
      redirect_to action: "index"
    end
  end

  def pay
    @item = Item.find(params[:format])
    if @item.soldout == "true"
      redirect_to root_path
    else
      Payjp::Charge.create(
      amount: @item.price,
      customer: @credit.customer_id,
      currency: 'jpy'
      )
      @item.update(
        soldout: "true"
      )
      @item.delivery.update(
        user: current_user
      )
      redirect_to root_path
    end
  end

  private

  def set_credit
    @credit = Credit.find_by(user_id: current_user.id) if Credit.find_by(user_id: current_user.id).present?
  end

  def set_api_key
    Payjp.api_key = Rails.application.credentials[:payjp][:secret_access_key]
  end

  def move_show
    redirect_to credit_path(@credit) if @credit.present?
  end

end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/index.html.haml
= render 'shared/main_header'
- breadcrumb :credit
= breadcrumbs separator: " &rsaquo; "
.u-s-content
  = render 'shared/navigation_bar'
  .payment
    .payment__content
      .payment__content__theme
        支払い方法
    .payment__moov-new
      =link_to new_credit_path do
        .payment__moov-new__box
          %i.far.fa-credit-card
          クレジットカードを追加する
    .payment__attention-sentence
      支払い方法について
      %i.fas.fa-chevron-right.icon
= render 'shared/main_footer'

app/views/credits/new.html.haml
= render 'shared/main_header'
- breadcrumb :credit_create
= breadcrumbs separator: " &rsaquo; "
.u-s-content
  = render 'shared/navigation_bar'
  .payment-page
    .payment-page__content
      .payment-page__content__theme
        支払い方法
      = form_with url: credits_path, method: :post, id: 'charge-form' do |f|
        .payment-page__content__top-box
          = f.label :カード番号, class: 'payment-page__content__top-box__text1'
          .payment-page__content__top-box__text2
            必須
        .payment-page__content__container1
          .payment-page__content__container1__form
            = f.text_field :card_number, type: 'text', class: 'payment-page__content__container1__form__box', placeholder: '半角数字のみ', maxlength: '16', id: 'payment_card_no'
        .payment-page__content__container1__icons
          .payment-page__content__container1__icons__icon
            = image_tag 'icon/visa.svg', width: '33px', height: '33px'
          .payment-page__content__container1__icons__icon
            = image_tag 'icon/jcb.svg', width: '33px', height: '33px'
          .payment-page__content__container1__icons__icon
            = image_tag 'icon/master-card.svg', width: '33px', height: '33px'
          .payment-page__content__container1__icons__icon
            = image_tag 'icon/american_express.svg', width: '33px', height: '33px'
          .payment-page__content__container1__icons__icon
            = image_tag 'icon/dinersclub.svg', width: '33px', height: '33px'
          .payment-page__content__container1__icons__icon
            = image_tag 'icon/discover.svg', width: '33px', height: '33px'

        .payment-page__content__middle-box
          = f.label :有効期限, class: 'payment-page__content__middle-box__text1'
          .payment-page__content__middle-box__text2
            必須
        .payment-page__content__container2
          .payment-page__content__container2__form-box
            .payment-page__content__container2__form-box__form-left
              = f.select :exp_month, [['01',1],['02',2],['03',3],['04',4],['05',5],['06',6],['07',7],['08',8],['09',9],['10',10],['11',11],['12',12]],{} , class: 'payment-page__content__container2__form-box__form-left__box', id: 'payment_card_expire_mm'
            .payment-page__content__container2__form-box__month
              月
            .payment-page__content__container2__form-box__form-right
              = f.select :exp_year, [['20',2020],['21',2021],['22',2022],['23',2023],['24',2024],['25',2025],['26',2026],['27',2027],['28',2028],['29',2029],['30',2030]],{} , class: 'payment-page__content__container2__form-box__form-left__box', id: 'payment_card_expire_yy'
            .payment-page__content__container2__form-box__year
              年
        .payment-page__content__bottom-box
          = f.label :セキュリティコード, class: 'payment-page__content__bottom-box__text1'
          .payment-page__content__bottom-box__text2
            必須
        .payment-page__content__container3
          .payment-page__content__container3__form
            = f.text_field :cvc, type: 'text', class: 'payment-page__content__container3__form__box', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: '4', id: 'payment_card_security_code', name: 'cvc'
          .payment-page__content__container3__help-box
            .payment-page__content__container3__help-box__icon
              ＊
            .payment-page__content__container3__help-box__text
              カード裏面の番号とは？
        = f.submit '追加する', class: 'payment-page__content__register-btn'
= render 'shared/main_footer'

app/views/credits/show.html.haml
= render 'shared/main_header'
- breadcrumb :credit_show
= breadcrumbs separator: " &rsaquo; "
.u-s-content
  = render 'shared/navigation_bar'
  .payment
    .payment__content
      .payment__content__theme
        クレジットカード情報
    .payment__card.payment__icon
      = image_tag "icon/#{@credit_information.brand.downcase}.svg", width: '50px', height: '35px'
    .payment__card
      = "**** **** **** " + @credit_information.last4
    .payment__card
      - exp_month = @credit_information.exp_month.to_s
      - exp_year = @credit_information.exp_year.to_s.slice(2,3)
      = exp_month + " / " + exp_year
    =link_to credit_path, method: :delete  do
      .payment__moov-new__box
        クレジットカードを削除する
= render 'shared/main_footer'