config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"
  resources :items do
    collection do
      get 'search'
      get 'get_category_children', defaults: { format: 'json' }
    end
    member do
      get 'buy'
    end
  end
  resources :users, only: [:show]
  resources :credits, except: [:edit, :update] do
    collection do
      get 'pay'
    end
  end
  resources :signups , only: [:new, :create] do
    collection do
      get 'identification'
      post 'address'
      post 'phone_number'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status
  belongs_to_active_hash :prefecture
  
  belongs_to :category
  belongs_to :user
  has_one :delivery, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  validates :name,             presence: true, length:{maximum: 40}
  validates :text,             presence: true, length:{maximum: 1000}
  validates :price,            presence: true
  validates :status_id,        presence: true
  validates :soldout,          presence: true
  validates :user_id,          presence: true
  validates :category_id,      presence: true

  def favorite?(user)
    favorite_users.include?(user)
  end

end  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_item, only: [:edit, :destroy, :show, :update, :buy]

  def index
    @items = Item.order("created_at DESC").limit(5)
    @fav = Item.find(Favorite.group(:item_id).order('count(item_id) DESC').limit(5).pluck(:item_id))
  end

  def new
    @item = Item.new
  end

  def create
    if params[:category_id] == nil
      render :new
    else
      @category = Category.find(params[:category_id])
      @item = Item.new(
        name: item_params[:name],
        text: item_params[:text],
        price: item_params[:price],
        brand: item_params[:brand],
        status_id: item_params[:status_id],
        category: @category,
        user_id: current_user.id
      )
      if @item.save
        count = 0
        if params[:picture1] != nil
          @picture1 = Picture.new(
            picture: params[:picture1],
            item_id: @item.id
          )
          count += 1 if @picture1.save
        end
        if params[:picture2] != nil
          @picture2 = Picture.new(
            picture: params[:picture2],
            item_id: @item.id
          )
          count += 1 if @picture2.save
        end
        if params[:picture3] != nil
          @picture3 = Picture.new(
            picture: params[:picture3],
            item_id: @item.id
          )
          count += 1 if @picture3.save
        end
        if params[:picture4] != nil
          @picture4 = Picture.new(
            picture: params[:picture4],
            item_id: @item.id
          )
          count += 1 if @picture4.save
        end
        if params[:picture5] != nil
          @picture5 = Picture.new(
            picture: params[:picture5],
            item_id: @item.id
          )
          count += 1 if @picture5.save
        end
        if count > 0
          Delivery.create(
          item_id: @item.id,
          deliverycharge_id: delivery_params[:deliverycharge_id],
          deliveryday_id: delivery_params[:deliveryday_id],
          prefecture_id: delivery_params[:prefecture_id]
          )
          redirect_to root_path
        else
          render :new
        end
      else
        render :new
      end
    end
  end

  def get_category_children
    @category_children = Category.find(params[:id]).children
  end

  def edit
  end

  def update
    if @item.user_id == current_user.id
      @item.update(item_params)
      @item.delivery.update(delivery_params)
      @item.pictures.each_with_index do |picture, index|
        if params[:"image#{index + 1}"] != "true" && params[:"params#{index + 1}"] != nil 
          picture.update(picture: params[:"params#{index + 1}"])
        elsif params[:"image#{index + 1}"] != "true" && params[:"params#{index + 1}"] ==  nil
          picture.destroy
        end
      end
      (5 - @item.pictures.length).times do |x|
        picture = Picture.create(
          picture: params[:"picture#{5 - x}"],
          item_id: @item.id
        )
      end
        redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
    @items = Item.all
    @items = @items.order("created_at DESC").limit(5)
    @item = Item.includes(:user, :delivery).find(params[:id])
    @favorites = Favorite.find_by(user_id: session[:user_id], item_id: @item)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def destroy
    if @item.user_id == current_user.id && @item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def buy
    if Credit.find_by(user_id: current_user.id).present?
      @credit = Credit.find_by(user_id: current_user.id)
      customer = Payjp::Customer.retrieve(@credit.customer_id)
      @credit_information = customer.cards.retrieve(@credit.card_id)
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.permit(:name,:text,:price,:brand,:status_id)
  end

  def delivery_params
    params.permit(:deliverycharge_id,:deliveryday_id,:prefecture_id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/buy.html.haml
= render 'shared/logo_header'
.buy-page
  .buy-page__buy-content
    .buy-page__buy-content__confirmation
      .buy-page__buy-content__confirmation__text
        購入内容の確認
    .buy-page__buy-content__item
      .buy-page__buy-content__item__box
        .buy-page__buy-content__item__box__img
          = image_tag @item.pictures[0].picture.url, width: "80px", height: "80px"
        .buy-page__buy-content__item__box__detail
          .buy-page__buy-content__item__box__detail__name
            =@item.name
          .buy-page__buy-content__item__box__detail__price
            ¥
            =@item.price
            -if @item.delivery.deliverycharge_id == 1
              (税込)送料込み
            -else
              (税込)送料別(着払い)
      .buy-page__buy-content__item__info
        .buy-page__buy-content__item__info__container
          .buy-page__buy-content__item__info__container__detail
            .buy-page__buy-content__item__info__container__detail__text
              支払い金額
            .buy-page__buy-content__item__info__container__detail__price
              ¥
              = @item.price
          .buy-page__buy-content__item__info__container__detail__point
            .buy-page__buy-content__item__info__container__detail__point__icon
              □ポイント使用(所持ポイント:P0)
          .buy-page__buy-content__item__info__container__method-box
            .buy-page__buy-content__item__info__container__method-box__text
              支払い方法
            .buy-page__buy-content__item__info__container__method-box__under
              -if current_user.credit.present?
                .buy-page__buy-content__item__info__container__method-box__under__credit
                  .payment__card
                    = image_tag "icon/#{@credit_information.brand.downcase}.svg", width: '50px', height: '35px'
                  .payment__card
                    = "**** **** **** " + @credit_information.last4
                  .payment__card
                    - exp_month = @credit_information.exp_month.to_s
                    - exp_year = @credit_information.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
              -else
                =link_to credits_path do
                  .buy-page__buy-content__item__info__container__method-box__under__icon
                    ◇登録してください
          .buy-page__buy-content__item__info__container__address-box
            .buy-page__buy-content__item__info__container__address-box__text
              配送先
            .buy-page__buy-content__item__info__container__address-box__under
              .buy-page__buy-content__item__info__container__address-box__under__address
                %div
                  〒
                  =current_user.address.post_number
                %div
                  =current_user.address.prefecture.name
                  =current_user.address.city
                  =current_user.address.house_number
                  =current_user.address.building
                %div
                  =current_user.first_name
                  =current_user.last_name
          .buy-page__buy-content__item__info__container__purchase
            -if @item.soldout == "false" && current_user.credit.present?
              = link_to pay_credits_path(@item) do
                .buy-page__buy-content__item__info__container__purchase__text
                  購入する
= render 'shared/logo_footer'

app/views/items/edit.html.haml
.exhibition
  = render 'shared/logo_header'
  .exhibition-main
    .exhibition-main__inner
      .in-containner
        .in-containner__header 商品の情報を入力
        %form.sell-form
        = form_with  id: "item-edit-form",method: :patch,url: item_path(@item), local: true do |f|
          .sell-form__uploder 
            .sell-form__uploder__head 
              .sell-form__uploder__head__text 出品画像
              .sell-form__uploder__head__require 必須
            %p.in- 最大5枚までアップロードできます。
            .sell-form__uploder__box
              .sell-form__uploder__box__lists
                -@item.pictures.each_with_index do |picture, index|
                  .sell-form__uploder__box__lists__list
                    = image_tag picture.picture.url
                    = f.hidden_field :"image#{index + 1}", value: "true"
                    %button.box-image__image-btn__delete{data: {picture: {id: "#label-picture#{index + 1}"}}}
                      削除
              .sell-form__uploder__box__field
                -5.times do |index|
                  = f.label :"picture#{index + 1}", "画像を選択", class: 'sell-form__uploder__box__field__picture', id: "label-picture#{index + 1}"
              .file_field_lists
                -@item.pictures.each_with_index do |picture, index|
                  = f.file_field :"picture#{index + 1}", class: 'sell-form__uploder__file'
                -(5 - @item.pictures.length).times do |index|
                  = f.file_field :"picture#{5 - index}", class: 'sell-form__uploder__file'
          .sell-form__content
            .sell-form__content__1
              %label.sell-form__content__1__head
                .sell-form__content__1__head__text 商品名
                .sell-form__content__1__head__require 必須
              =f.text_field :name, class:'sell-form__content__1__form__input',value: @item.name
              .exhibition_error_messages#error_name
            .sell-form__content__2
              .sell-form__content__2__head
                .sell-form__content__2__head__text 商品の説明
                .sell-form__content__2__head__require 必須
              =f.text_area :text, class:'sell-form__content__2__input', value: @item.text ,placeholder:'商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'
              .exhibition_error_messages#error_text
          .sell-form__content__clearfix 
            .sell-form__content__clearfix__sub 商品詳細
            .sell-form__content__clearfix__form
              #category_lists
                .sell-form__content__clearfix__form__group
                  %label.sell-form__content__clearfix__form__group__head
                    .sell-form__content__clearfix__form__group__head__text カテゴリー
                    .sell-form__content__clearfix__form__group__head__require 必須
                  .sell-form__content__clearfix__form__group__field
                    = f.select :grandparent_category_id, Category.where(category_id: nil) .map { |category| [category.name, category.id] },{prompt:"--",selected:@item.category.parent.parent.id}
                  .sell-form__content__clearfix__form__group__field#children_category
                    = f.select :parent_category_id, Category.where(category_id: @item.category.parent.parent.id) .map { |category| [category.name, category.id] },{prompt: "--", selected: @item.category.parent.id}
                  .sell-form__content__clearfix__form__group__field#grandchildren_category
                    = f.select :category_id, Category.where(category_id: @item.category.parent.id) .map { |category| [category.name, category.id] },{prompt: "--", selected:@item.category_id}
              .exhibition_error_messages#error_category
              .sell-form__content__clearfix__form__group
                .sell-form__content__clearfix__sub 
                .sell-form__content__clearfix__form
                  .sell-form__content__clearfix__form__group
                    %label.sell-form__content__clearfix__form__group__head
                      .sell-form__content__clearfix__form__group__head__text ブランド
                      .sell-form__content__clearfix__form__group__head__require 任意
                    .sell-form__content__clearfix__form__group__field
                      %i.in-select__button
                      = f.text_field :brand, class:'sell-form__content__1__form__input',value: @item.brand ,placeholder: '例）アディダス'
              .sell-form__content__clearfix__form__group
                .sell-form__content__clearfix__sub 
                .sell-form__content__clearfix__form
                  .sell-form__content__clearfix__form__group
                    %label.sell-form__content__clearfix__form__group__head
                      .sell-form__content__clearfix__form__group__head__text 商品の状態
                      .sell-form__content__clearfix__form__group__head__require 必須
                    .sell-form__content__clearfix__form__group__field
                      %i.in-select__button
                      = f.collection_select :status_id, Status.all, :id, :name,{prompt: "--",selected:@item.status_id}
                    .exhibition_error_messages#error_status
          .sell-form__content__clearfix 
            .sell-form__content__clearfix__sub 配送について
            .sell-form__content__clearfix__form
              .sell-form__content__clearfix__form__group
                %label.sell-form__content__clearfix__form__group__head
                  .sell-form__content__clearfix__form__group__head__text 配送料の負担
                  .sell-form__content__clearfix__form__group__head__require 必須
                .sell-form__content__clearfix__form__group__field
                  %i.in-select__button
                  = f.collection_select :deliverycharge_id, Deliverycharge.all, :id, :name,{prompt: "--",selected: @item.delivery.deliverycharge_id}
                .exhibition_error_messages#error_deliverycharge
              .sell-form__content__clearfix__form__group
                .sell-form__content__clearfix__sub 
                .sell-form__content__clearfix__form
                  .sell-form__content__clearfix__form__group
                    %label.sell-form__content__clearfix__form__group__head
                      .sell-form__content__clearfix__form__group__head__text 配送元の地域
                      .sell-form__content__clearfix__form__group__head__require 必須
                    .sell-form__content__clearfix__form__group__field
                      %i.in-select__button
                      = f.collection_select :prefecture_id, Prefecture.all, :id, :name,{prompt: "--",selected: @item.delivery.prefecture_id}
              .sell-form__content__clearfix__form__group
                %label.sell-form__content__clearfix__form__group__head
                  .sell-form__content__clearfix__form__group__head__text 配送までの日数
                  .sell-form__content__clearfix__form__group__head__require 必須
                .sell-form__content__clearfix__form__group__field
                  %i.in-select__button
                  = f.collection_select :deliveryday_id, Deliveryday.all, :id, :name,{prompt: "--",selected: @item.delivery.deliveryday_id}
                .exhibition_error_messages#error_deliveryday
          .sell-form__price
            .sell-form__price__left 販売価格(300~9,999,999)
            .sell-form__price__right
              .sell-form__price__right__box
                %label.sell-form__price__right__box__head
                  .sell-form__price__right__box__head__box
                    .sell-form__price__right__box__head__box__price 価格
                    .sell-form__price__right__box__head__box__require 必須
                  .sell-form__price__right__box__head__form
                    ¥
                    =f.number_field :price, id: "price_calc", class: "sell-form__price__right__box__head__form__price",placeholder: "例) 300", value:@item.price
                .sell-form__price__right__text 
                  .sell-form__price__right__text__l 
                    販売手数料（１０％）
                  .sell-form__price__right__text__r -
                .sell-form__price__right__rieki 
                  .sell-form__price__right__rieki__l 
                    販売利益
                  .sell-form__price__right__rieki__r -
              .exhibition_error_messages#error_price
          .sell-form__btn__box
            .sell-form__btn__box__text
              禁止されている出品、行為を必ずご確認ください。
              %br
                またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
              %br
                また、出品をもちまして加盟店規約に同意したことになります。
            =f.submit "更新する", class: "sell-form__btn__box__exhibition"
            .sell-form__btn__box__return もどる
= render 'shared/logo_footer'

app/views/items/search.html.haml
= render 'shared/main_header'
.search
  .search__nav
  .search__main
    .search__main__title
    .search__main__content
      - @items.each do |item|
        .top-category__lists__list1
          .top-category__lists__list1__img
            = link_to item_path(item) do
              = image_tag item.pictures[0].picture.url,size: "188x188"
          - if item.soldout == "true"
            .top-category__lists__list1__border-box
            .top-category__lists__list1__text-box
              .top-category__lists__list1__text-box__sold-out
                SOLD
          .top-category__lists__list1__text-box__name
            = item.name
          .top-category__lists__list1__text-box__box
            .top-category__lists__list1__text-box__box__price
              = item.price
            .top-category__lists__list1__text-box__box__like
              ♡ 2
          .top-category__lists__list1__text-box__tax
            (税込)
= render 'shared/main_footer'
- if user_signed_in?
  = render 'shared/main_exhibition-btn'

app/views/items/show.html.haml
= render 'shared/main_header'
.item-show
  .item-show__page
    .item-show__page__box
      .item-show__page__box__name
        = @item.name
      .item-show__page__box__content
        .item-show__page__box__content__img
          #picturepreview
            = image_tag @item.pictures[0].picture.url, width: "290px", height: "290px"
            - if @item.soldout == "true"
              .top-category__lists__list1__border-box
              .top-category__lists__list1__text-box
                .top-category__lists__list1__text-box__sold-out
                  SOLD
          .picture
            - @item.pictures.each do |picture|
              = image_tag picture.picture.url, width: "54.3px", height: "54.3px", class: "hoge"
        .item-show__page__box__content__table
          %table{border: "1"}
            %tr
              %th 出品者
              %td
                = link_to user_path(@item.user) do
                  = @item.user.nickname
            %tr
              %th カテゴリー
              %td
                = @item.category.name 
            %tr
              %th ブランド
              %td
                = @item.brand
            %tr
              %th 商品の状態
              %td
                = @item.status.name
            %tr
              %th 配送料の負担
              %td
                = @item.delivery.deliverycharge.name
            %tr
              %th 配送元地域
              %td
                = @item.user.address.prefecture.name
                = @item.user.address.city
            %tr
              %th 発送日の目安
              %td
                = @item.delivery.deliveryday.name
      .item-show__page__box__price-box
        .item-show__page__box__price-box__price
          ¥
          = @item.price
        .item-show__page__box__price-box__tax
          (税込)
        -if @item.delivery.deliverycharge.name == "送料込み(出品者負担)"
          .item-show__page__box__price-box__shipping-fee
            送料込み
        -else
          .item-show__page__box__price-box__shipping-fee
            送料別
      - if @item.user == current_user
        = link_to edit_item_path(@item) do
          .item-show__page__box__buy-btn
            編集
        = link_to item_path(@item), method: :delete do
          .item-show__page__box__delete-btn
            削除
      - else 
        = link_to buy_item_path(@item) do
          .item-show__page__box__buy-btn
            購入画面に進む
      .item-show__page__box__text
        この商品はFURIMA便を利用しているため、アプリからのみ購入できます。
      .item-show__page__box__description
        .item-show__page__box__description__text
          [商品説明]
          = @item.text
        .item-show__page__box__description__container
          .item-show__page__box__description__container__left-box
            .item-show__page__box__description__container__left-box__good-btn
              - if @item.favorite?(current_user)
                %i.fa.fa-heart.red{data:{ids:{"item": @item.id,"user": current_user.id}}}
              - else
                %i.fa.fa-heart{data:{ids:{"item": @item.id,"user": current_user.id}}}
              %p#favorite-count 
                = @item.favorites.length
            .item-show__page__box__description__container__left-box__report-btn
              🇯🇵  不適切な商品の報告
          .item-show__page__box__description__container__lock-text
            🔑  あんしん・あんぜんへの取り組み
  = form_with model: @comment, method: :post,url: item_comments_path(@item), local: true, id: "new_comment"do |f|
    .item-show__page__show-message
      .item-show__page__show-message__container
        .item-show__page__show-message__container__content
          .item-show__page__show-message__container__content__text
            相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
          =f.text_area :text, class:"item-show__page__show-message__container__content__text-box"
          =f.submit "コメントする",class:"item-show__page__show-message__container__content__comment" 
          .comments
            %h4 ＜コメント一覧＞
            - if @comments
              - @comments.each do |comment|
                %p
                  %strong
                    = link_to comment.user.nickname, "/items/#{comment.item_id}"
                    ：
                  = comment.text
           
          
    .item-show__page__show-icons
      .item-show__page__show-icons__container
        .item-show__page__show-icons__container__facebook
          %i.fab.fa-twitter
        .item-show__page__show-icons__container__twitter 
          %i.fab.fa-facebook
        .item-show__page__show-icons__container__pinterest
          %i.fab.fa-line
    .item-show__page__other-item
      .item-show__page__other-item__text
        = @item.user.nickname
        さんのその他の出品
      .item-show__page__other-item__lists
        - @items.each do |item|
          = link_to item_path(item) do
            .item-show__page__other-item__lists__list1
              .item-show__page__other-item__lists__list1__img
                = image_tag item.pictures[0].picture.url,size: "188x188"
                - if item.soldout == "true"
                  .top-category__lists__list1__border-box
                  .top-category__lists__list1__text-box
                    .top-category__lists__list1__text-box__sold-out
                      SOLD
              .item-show__page__other-item__lists__list1__text
                .item-show__page__other-item__lists__list1__text__name
                  = item.name
                .item-show__page__other-item__lists__list1__text__low-box
                  .item-show__page__other-item__lists__list1__text__low-box__price
                    = item.price
                  .item-show__page__other-item__lists__list1__text__low-box__good
                    %i.fa.fa-heart
                    %p#favorite-count 
                      = item.favorites.length
- breadcrumb :item, @item
= breadcrumbs separator: " &rsaquo; "
= render 'shared/main_footer'

:javascript
  $(function(){
    $(document).on("click",".fa-heart",function(){
      var item = $(this).data("ids-item");
      var user = $(this).data("ids-user");
      let count = $("#favorite-count").text().trim();
        console.log(+count + 1);
      if($(this).hasClass("red")){
        $.ajax({
          type: 'DELETE',
          url: `/favorites/${item}`,
          data: {item_id: item, user_id: user},
          dataType: 'json'
        })
        .done(function(){
          console.log('成功');
          $(".fa-heart").removeClass("red");
          $("#favorite-count").empty();
          $("#favorite-count").append(+count - 1);
        })
        .fail(function(){
          console.log('失敗');
        });
      }else{
        $.ajax({
          type: 'POST',
          url: `/favorites`,
          data: {item_id: item},
          dataType: 'json'
        })
        .done(function(){
          console.log('成功');
          $(".fa-heart").addClass("red");
          //$("#favorite-count").replace(count, +count + 1);
          $("#favorite-count").empty();
          $("#favorite-count").append(+count + 1);
        })
        .fail(function(){
          console.log('失敗');
        });
      }
    });
  });